/* Philippine Address Data — Regions, Provinces, Cities/Municipalities, Postal Codes */

const PH_REGIONS = [
  { key: "ncr",  label: "NCR – National Capital Region",                  shipping: "ncr"      },
  { key: "car",  label: "CAR – Cordillera Administrative Region",          shipping: "luzon"    },
  { key: "r1",   label: "Region I – Ilocos Region",                        shipping: "luzon"    },
  { key: "r2",   label: "Region II – Cagayan Valley",                      shipping: "luzon"    },
  { key: "r3",   label: "Region III – Central Luzon",                      shipping: "luzon"    },
  { key: "r4a",  label: "Region IV-A – CALABARZON",                        shipping: "luzon"    },
  { key: "r4b",  label: "Region IV-B – MIMAROPA",                          shipping: "luzon"    },
  { key: "r5",   label: "Region V – Bicol Region",                         shipping: "luzon"    },
  { key: "r6",   label: "Region VI – Western Visayas",                     shipping: "visayas"  },
  { key: "r7",   label: "Region VII – Central Visayas",                    shipping: "visayas"  },
  { key: "r8",   label: "Region VIII – Eastern Visayas",                   shipping: "visayas"  },
  { key: "r9",   label: "Region IX – Zamboanga Peninsula",                 shipping: "mindanao" },
  { key: "r10",  label: "Region X – Northern Mindanao",                    shipping: "mindanao" },
  { key: "r11",  label: "Region XI – Davao Region",                        shipping: "mindanao" },
  { key: "r12",  label: "Region XII – SOCCSKSARGEN",                       shipping: "mindanao" },
  { key: "r13",  label: "Region XIII – Caraga",                            shipping: "mindanao" },
  { key: "barmm",label: "BARMM – Bangsamoro Autonomous Region",            shipping: "mindanao" },
];

const PH_PROVINCES = {
  ncr:   [{ key: "metro_manila",       label: "Metro Manila" }],
  car:   [
    { key: "abra",            label: "Abra" },
    { key: "apayao",          label: "Apayao" },
    { key: "benguet",         label: "Benguet" },
    { key: "baguio",          label: "Baguio City" },
    { key: "ifugao",          label: "Ifugao" },
    { key: "kalinga",         label: "Kalinga" },
    { key: "mt_province",     label: "Mountain Province" },
  ],
  r1: [
    { key: "ilocos_norte",    label: "Ilocos Norte" },
    { key: "ilocos_sur",      label: "Ilocos Sur" },
    { key: "la_union",        label: "La Union" },
    { key: "pangasinan",      label: "Pangasinan" },
  ],
  r2: [
    { key: "batanes",         label: "Batanes" },
    { key: "cagayan",         label: "Cagayan" },
    { key: "isabela",         label: "Isabela" },
    { key: "nueva_vizcaya",   label: "Nueva Vizcaya" },
    { key: "quirino",         label: "Quirino" },
  ],
  r3: [
    { key: "aurora",          label: "Aurora" },
    { key: "bataan",          label: "Bataan" },
    { key: "bulacan",         label: "Bulacan" },
    { key: "nueva_ecija",     label: "Nueva Ecija" },
    { key: "pampanga",        label: "Pampanga" },
    { key: "tarlac",          label: "Tarlac" },
    { key: "zambales",        label: "Zambales" },
  ],
  r4a: [
    { key: "batangas",        label: "Batangas" },
    { key: "cavite",          label: "Cavite" },
    { key: "laguna",          label: "Laguna" },
    { key: "quezon",          label: "Quezon" },
    { key: "rizal",           label: "Rizal" },
  ],
  r4b: [
    { key: "marinduque",      label: "Marinduque" },
    { key: "occ_mindoro",     label: "Occidental Mindoro" },
    { key: "or_mindoro",      label: "Oriental Mindoro" },
    { key: "palawan",         label: "Palawan" },
    { key: "romblon",         label: "Romblon" },
  ],
  r5: [
    { key: "albay",           label: "Albay" },
    { key: "cam_norte",       label: "Camarines Norte" },
    { key: "cam_sur",         label: "Camarines Sur" },
    { key: "catanduanes",     label: "Catanduanes" },
    { key: "masbate",         label: "Masbate" },
    { key: "sorsogon",        label: "Sorsogon" },
  ],
  r6: [
    { key: "aklan",           label: "Aklan" },
    { key: "antique",         label: "Antique" },
    { key: "capiz",           label: "Capiz" },
    { key: "guimaras",        label: "Guimaras" },
    { key: "iloilo",          label: "Iloilo" },
    { key: "neg_occ",         label: "Negros Occidental" },
  ],
  r7: [
    { key: "bohol",           label: "Bohol" },
    { key: "cebu",            label: "Cebu" },
    { key: "neg_or",          label: "Negros Oriental" },
    { key: "siquijor",        label: "Siquijor" },
  ],
  r8: [
    { key: "biliran",         label: "Biliran" },
    { key: "e_samar",         label: "Eastern Samar" },
    { key: "leyte",           label: "Leyte" },
    { key: "n_samar",         label: "Northern Samar" },
    { key: "samar",           label: "Samar (Western Samar)" },
    { key: "s_leyte",         label: "Southern Leyte" },
  ],
  r9: [
    { key: "zamboanga_city",  label: "Zamboanga City" },
    { key: "zam_norte",       label: "Zamboanga del Norte" },
    { key: "zam_sur",         label: "Zamboanga del Sur" },
    { key: "zam_sibugay",     label: "Zamboanga Sibugay" },
  ],
  r10: [
    { key: "bukidnon",        label: "Bukidnon" },
    { key: "camiguin",        label: "Camiguin" },
    { key: "lanao_norte",     label: "Lanao del Norte" },
    { key: "mis_occ",         label: "Misamis Occidental" },
    { key: "mis_or",          label: "Misamis Oriental" },
  ],
  r11: [
    { key: "comval",          label: "Davao de Oro (Compostela Valley)" },
    { key: "davao_city",      label: "Davao City" },
    { key: "davao_norte",     label: "Davao del Norte" },
    { key: "davao_sur",       label: "Davao del Sur" },
    { key: "davao_occ",       label: "Davao Occidental" },
    { key: "davao_or",        label: "Davao Oriental" },
  ],
  r12: [
    { key: "cotabato",        label: "Cotabato (North Cotabato)" },
    { key: "sarangani",       label: "Sarangani" },
    { key: "s_cotabato",      label: "South Cotabato" },
    { key: "sultan_kudarat",  label: "Sultan Kudarat" },
  ],
  r13: [
    { key: "agusan_norte",    label: "Agusan del Norte" },
    { key: "agusan_sur",      label: "Agusan del Sur" },
    { key: "dinagat",         label: "Dinagat Islands" },
    { key: "surigao_norte",   label: "Surigao del Norte" },
    { key: "surigao_sur",     label: "Surigao del Sur" },
  ],
  barmm: [
    { key: "basilan",         label: "Basilan" },
    { key: "lanao_sur",       label: "Lanao del Sur" },
    { key: "maguindanao_n",   label: "Maguindanao del Norte" },
    { key: "maguindanao_s",   label: "Maguindanao del Sur" },
    { key: "sulu",            label: "Sulu" },
    { key: "tawi_tawi",       label: "Tawi-Tawi" },
  ],
};

const PH_CITIES = {
  metro_manila: [
    { name: "Caloocan",      postal: "1400" },
    { name: "Las Piñas",     postal: "1740" },
    { name: "Makati",        postal: "1200" },
    { name: "Malabon",       postal: "1470" },
    { name: "Mandaluyong",   postal: "1550" },
    { name: "Manila",        postal: "1000" },
    { name: "Marikina",      postal: "1800" },
    { name: "Muntinlupa",    postal: "1770" },
    { name: "Navotas",       postal: "1485" },
    { name: "Parañaque",     postal: "1700" },
    { name: "Pasay",         postal: "1300" },
    { name: "Pasig",         postal: "1600" },
    { name: "Pateros",       postal: "1620" },
    { name: "Quezon City",   postal: "1100" },
    { name: "San Juan",      postal: "1500" },
    { name: "Taguig",        postal: "1630" },
    { name: "Valenzuela",    postal: "1440" },
  ],
  abra: [
    { name: "Bangued",       postal: "2800" },
    { name: "Boliney",       postal: "2802" },
    { name: "Bucay",         postal: "2806" },
    { name: "Bucloc",        postal: "2803" },
    { name: "Daguioman",     postal: "2807" },
    { name: "Danglas",       postal: "2804" },
    { name: "Dolores",       postal: "2801" },
    { name: "La Paz",        postal: "2812" },
    { name: "Lacub",         postal: "2808" },
    { name: "Lagangilang",   postal: "2809" },
    { name: "Lagayan",       postal: "2810" },
    { name: "Langiden",      postal: "2811" },
    { name: "Licuan-Baay",   postal: "2813" },
    { name: "Luba",          postal: "2814" },
    { name: "Malibcong",     postal: "2815" },
    { name: "Manabo",        postal: "2816" },
    { name: "Peñarrubia",    postal: "2817" },
    { name: "Pidigan",       postal: "2818" },
    { name: "Pilar",         postal: "2820" },
    { name: "Sallapadan",    postal: "2821" },
    { name: "San Isidro",    postal: "2822" },
    { name: "San Juan",      postal: "2823" },
    { name: "San Quintin",   postal: "2824" },
    { name: "Tayum",         postal: "2825" },
    { name: "Tineg",         postal: "2826" },
    { name: "Tubo",          postal: "2827" },
    { name: "Villaviciosa",  postal: "2828" },
  ],
  apayao: [
    { name: "Calanasan",     postal: "3814" },
    { name: "Flora",         postal: "3802" },
    { name: "Kabugao",       postal: "3800" },
    { name: "Luna",          postal: "3801" },
    { name: "Pudtol",        postal: "3803" },
    { name: "Santa Marcela", postal: "3804" },
  ],
  benguet: [
    { name: "Atok",          postal: "2612" },
    { name: "Bakun",         postal: "2619" },
    { name: "Bokod",         postal: "2605" },
    { name: "Buguias",       postal: "2607" },
    { name: "Itogon",        postal: "2604" },
    { name: "Kabayan",       postal: "2616" },
    { name: "Kapangan",      postal: "2613" },
    { name: "Kibungan",      postal: "2618" },
    { name: "La Trinidad",   postal: "2601" },
    { name: "Mankayan",      postal: "2608" },
    { name: "Sablan",        postal: "2600" },
    { name: "Tuba",          postal: "2603" },
    { name: "Tublay",        postal: "2615" },
  ],
  baguio: [
    { name: "Baguio City",   postal: "2600" },
  ],
  ifugao: [
    { name: "Aguinaldo",     postal: "3605" },
    { name: "Alfonso Lista", postal: "3614" },
    { name: "Asipulo",       postal: "3618" },
    { name: "Banaue",        postal: "3601" },
    { name: "Hingyon",       postal: "3602" },
    { name: "Hungduan",      postal: "3604" },
    { name: "Kiangan",       postal: "3605" },
    { name: "Lagawe",        postal: "3600" },
    { name: "Lamut",         postal: "3613" },
    { name: "Mayoyao",       postal: "3606" },
    { name: "Tinoc",         postal: "3607" },
  ],
  kalinga: [
    { name: "Balbalan",      postal: "3704" },
    { name: "Lubuagan",      postal: "3703" },
    { name: "Pasil",         postal: "3702" },
    { name: "Pinukpuk",      postal: "3705" },
    { name: "Rizal",         postal: "3708" },
    { name: "Tabuk City",    postal: "3800" },
    { name: "Tanudan",       postal: "3701" },
    { name: "Tinglayan",     postal: "3706" },
  ],
  mt_province: [
    { name: "Barlig",        postal: "2617" },
    { name: "Bauko",         postal: "2616" },
    { name: "Besao",         postal: "2614" },
    { name: "Bontoc",        postal: "2616" },
    { name: "Natonin",       postal: "2617" },
    { name: "Paracelis",     postal: "2619" },
    { name: "Sagada",        postal: "2619" },
    { name: "Tadian",        postal: "2612" },
  ],
  ilocos_norte: [
    { name: "Bacarra",       postal: "2916" },
    { name: "Badoc",         postal: "2904" },
    { name: "Bangui",        postal: "2918" },
    { name: "Banna",         postal: "2914" },
    { name: "Batac City",    postal: "2906" },
    { name: "Burgos",        postal: "2913" },
    { name: "Currimao",      postal: "2903" },
    { name: "Dingras",       postal: "2911" },
    { name: "Dumalneg",      postal: "2919" },
    { name: "Laoag City",    postal: "2900" },
    { name: "Marcos",        postal: "2907" },
    { name: "Nueva Era",     postal: "2912" },
    { name: "Pagudpud",      postal: "2919" },
    { name: "Paoay",         postal: "2910" },
    { name: "Pasuquin",      postal: "2917" },
    { name: "Piddig",        postal: "2915" },
    { name: "Pinili",        postal: "2922" },
    { name: "San Nicolas",   postal: "2901" },
    { name: "Sarrat",        postal: "2905" },
    { name: "Solsona",       postal: "2908" },
    { name: "Vintar",        postal: "2909" },
  ],
  ilocos_sur: [
    { name: "Alilem",        postal: "2705" },
    { name: "Bantay",        postal: "2727" },
    { name: "Cabugao",       postal: "2732" },
    { name: "Candon City",   postal: "2700" },
    { name: "Cervantes",     postal: "2703" },
    { name: "Galimuyod",     postal: "2712" },
    { name: "Magsingal",     postal: "2730" },
    { name: "Narvacan",      postal: "2713" },
    { name: "San Esteban",   postal: "2734" },
    { name: "Santa Cruz",    postal: "2723" },
    { name: "Santa Lucia",   postal: "2702" },
    { name: "Santa Maria",   postal: "2733" },
    { name: "Sinait",        postal: "2729" },
    { name: "Tagudin",       postal: "2717" },
    { name: "Vigan City",    postal: "2700" },
  ],
  la_union: [
    { name: "Agoo",          postal: "2504" },
    { name: "Aringay",       postal: "2503" },
    { name: "Bacnotan",      postal: "2515" },
    { name: "Bauang",        postal: "2501" },
    { name: "Naguilian",     postal: "2506" },
    { name: "Rosario",       postal: "2519" },
    { name: "San Fernando City", postal: "2500" },
    { name: "San Juan",      postal: "2521" },
    { name: "Santo Tomas",   postal: "2504" },
    { name: "Tubao",         postal: "2503" },
  ],
  pangasinan: [
    { name: "Alaminos City", postal: "2404" },
    { name: "Bayambang",     postal: "2423" },
    { name: "Binalonan",     postal: "2436" },
    { name: "Bolinao",       postal: "2406" },
    { name: "Dagupan City",  postal: "2400" },
    { name: "Laoac",         postal: "2437" },
    { name: "Lingayen",      postal: "2401" },
    { name: "Malasiqui",     postal: "2421" },
    { name: "Manaoag",       postal: "2430" },
    { name: "Mangaldan",     postal: "2432" },
    { name: "Pozorrubio",    postal: "2434" },
    { name: "Rosales",       postal: "2441" },
    { name: "San Carlos City", postal: "2420" },
    { name: "Santa Barbara", postal: "2419" },
    { name: "Urdaneta City", postal: "2428" },
    { name: "Villasis",      postal: "2427" },
  ],
  batanes: [
    { name: "Basco",         postal: "3900" },
    { name: "Itbayat",       postal: "3908" },
    { name: "Ivana",         postal: "3902" },
    { name: "Mahatao",       postal: "3904" },
    { name: "Sabtang",       postal: "3901" },
    { name: "Uyugan",        postal: "3906" },
  ],
  cagayan: [
    { name: "Aparri",        postal: "3515" },
    { name: "Baggao",        postal: "3506" },
    { name: "Ballesteros",   postal: "3516" },
    { name: "Claveria",      postal: "3505" },
    { name: "Gattaran",      postal: "3504" },
    { name: "Gonzaga",       postal: "3512" },
    { name: "Lal-lo",        postal: "3509" },
    { name: "Lasam",         postal: "3511" },
    { name: "Piat",          postal: "3503" },
    { name: "Sanchez-Mira",  postal: "3502" },
    { name: "Santa Ana",     postal: "3519" },
    { name: "Solana",        postal: "3513" },
    { name: "Tuguegarao City", postal: "3500" },
  ],
  isabela: [
    { name: "Cauayan City",  postal: "3305" },
    { name: "Echague",       postal: "3309" },
    { name: "Ilagan City",   postal: "3300" },
    { name: "Naguilian",     postal: "3302" },
    { name: "Ramon",         postal: "3310" },
    { name: "San Mateo",     postal: "3321" },
    { name: "Santa Maria",   postal: "3331" },
    { name: "Santiago City", postal: "3311" },
    { name: "Tumauini",      postal: "3325" },
  ],
  nueva_vizcaya: [
    { name: "Ambaguio",      postal: "3702" },
    { name: "Aritao",        postal: "3706" },
    { name: "Bagabag",       postal: "3712" },
    { name: "Bambang",       postal: "3702" },
    { name: "Bayombong",     postal: "3700" },
    { name: "Diadi",         postal: "3705" },
    { name: "Kayapa",        postal: "3704" },
    { name: "Santa Fe",      postal: "3703" },
    { name: "Solano",        postal: "3711" },
    { name: "Villaverde",    postal: "3701" },
  ],
  quirino: [
    { name: "Aglipay",       postal: "3401" },
    { name: "Cabarroguis",   postal: "3400" },
    { name: "Diffun",        postal: "3402" },
    { name: "Maddela",       postal: "3404" },
    { name: "Nagtipunan",    postal: "3403" },
    { name: "Saguday",       postal: "3405" },
  ],
  aurora: [
    { name: "Baler",         postal: "3200" },
    { name: "Casiguran",     postal: "3204" },
    { name: "Dilasag",       postal: "3205" },
    { name: "Dinalungan",    postal: "3206" },
    { name: "Dingalan",      postal: "3207" },
    { name: "Dipaculao",     postal: "3203" },
    { name: "Maria Aurora",  postal: "3202" },
    { name: "San Luis",      postal: "3201" },
  ],
  bataan: [
    { name: "Abucay",        postal: "2114" },
    { name: "Bagac",         postal: "2107" },
    { name: "Balanga City",  postal: "2100" },
    { name: "Dinalupihan",   postal: "2110" },
    { name: "Hermosa",       postal: "2111" },
    { name: "Limay",         postal: "2103" },
    { name: "Mariveles",     postal: "2105" },
    { name: "Morong",        postal: "2109" },
    { name: "Orani",         postal: "2112" },
    { name: "Orion",         postal: "2102" },
    { name: "Pilar",         postal: "2101" },
    { name: "Samal",         postal: "2113" },
  ],
  bulacan: [
    { name: "Angat",         postal: "3012" },
    { name: "Balagtas",      postal: "3016" },
    { name: "Baliuag",       postal: "3006" },
    { name: "Bocaue",        postal: "3018" },
    { name: "Bulakan",       postal: "3017" },
    { name: "Bustos",        postal: "3007" },
    { name: "Calumpit",      postal: "3003" },
    { name: "Guiguinto",     postal: "3015" },
    { name: "Hagonoy",       postal: "3002" },
    { name: "Malolos City",  postal: "3000" },
    { name: "Marilao",       postal: "3019" },
    { name: "Meycauayan City", postal: "3020" },
    { name: "Norzagaray",    postal: "3013" },
    { name: "Obando",        postal: "3021" },
    { name: "Pandi",         postal: "3014" },
    { name: "Paombong",      postal: "3001" },
    { name: "Plaridel",      postal: "3004" },
    { name: "Pulilan",       postal: "3005" },
    { name: "San Ildefonso", postal: "3010" },
    { name: "San Jose del Monte City", postal: "3023" },
    { name: "San Miguel",    postal: "3011" },
    { name: "San Rafael",    postal: "3008" },
    { name: "Santa Maria",   postal: "3022" },
  ],
  nueva_ecija: [
    { name: "Cabanatuan City", postal: "3100" },
    { name: "Cabiao",        postal: "3107" },
    { name: "Gapan City",    postal: "3105" },
    { name: "Guimba",        postal: "3115" },
    { name: "Jaen",          postal: "3109" },
    { name: "Munoz City",    postal: "3119" },
    { name: "Palayan City",  postal: "3132" },
    { name: "Peñaranda",     postal: "3108" },
    { name: "San Jose City", postal: "3121" },
    { name: "San Leonardo",  postal: "3102" },
    { name: "Santa Rosa",    postal: "3101" },
    { name: "Talavera",      postal: "3114" },
    { name: "Zaragoza",      postal: "3110" },
  ],
  pampanga: [
    { name: "Angeles City",  postal: "2009" },
    { name: "Apalit",        postal: "2016" },
    { name: "Arayat",        postal: "2012" },
    { name: "Bacolor",       postal: "2001" },
    { name: "Candaba",       postal: "2013" },
    { name: "Floridablanca", postal: "2006" },
    { name: "Guagua",        postal: "2003" },
    { name: "Lubao",         postal: "2005" },
    { name: "Mabalacat City", postal: "2010" },
    { name: "Macabebe",      postal: "2018" },
    { name: "Magalang",      postal: "2011" },
    { name: "Mexico",        postal: "2021" },
    { name: "Minalin",       postal: "2019" },
    { name: "Porac",         postal: "2008" },
    { name: "San Fernando City", postal: "2000" },
    { name: "San Luis",      postal: "2014" },
    { name: "San Simon",     postal: "2015" },
    { name: "Santa Ana",     postal: "2022" },
    { name: "Santa Rita",    postal: "2002" },
    { name: "Santo Tomas",   postal: "2020" },
    { name: "Sasmuan",       postal: "2007" },
  ],
  tarlac: [
    { name: "Anao",          postal: "2310" },
    { name: "Bamban",        postal: "2317" },
    { name: "Camiling",      postal: "2306" },
    { name: "Capas",         postal: "2315" },
    { name: "Concepcion",    postal: "2316" },
    { name: "Gerona",        postal: "2302" },
    { name: "La Paz",        postal: "2314" },
    { name: "Moncada",       postal: "2308" },
    { name: "Paniqui",       postal: "2307" },
    { name: "San Clemente",  postal: "2312" },
    { name: "San Jose",      postal: "2303" },
    { name: "San Manuel",    postal: "2309" },
    { name: "Santa Ignacia", postal: "2303" },
    { name: "Tarlac City",   postal: "2300" },
    { name: "Victoria",      postal: "2318" },
  ],
  zambales: [
    { name: "Botolan",       postal: "2202" },
    { name: "Cabangan",      postal: "2203" },
    { name: "Candelaria",    postal: "2212" },
    { name: "Castillejos",   postal: "2208" },
    { name: "Iba",           postal: "2201" },
    { name: "Masinloc",      postal: "2211" },
    { name: "Olongapo City", postal: "2200" },
    { name: "San Antonio",   postal: "2206" },
    { name: "San Felipe",    postal: "2204" },
    { name: "San Marcelino", postal: "2207" },
    { name: "San Narciso",   postal: "2213" },
    { name: "Santa Cruz",    postal: "2213" },
    { name: "Subic",         postal: "2209" },
  ],
  batangas: [
    { name: "Agoncillo",     postal: "4211" },
    { name: "Balayan",       postal: "4213" },
    { name: "Batangas City", postal: "4200" },
    { name: "Bauan",         postal: "4201" },
    { name: "Calaca",        postal: "4212" },
    { name: "Calatagan",     postal: "4215" },
    { name: "Ibaan",         postal: "4230" },
    { name: "Lemery",        postal: "4209" },
    { name: "Lian",          postal: "4216" },
    { name: "Lipa City",     postal: "4217" },
    { name: "Lobo",          postal: "4229" },
    { name: "Mabini",        postal: "4202" },
    { name: "Nasugbu",       postal: "4231" },
    { name: "Rosario",       postal: "4225" },
    { name: "San Jose",      postal: "4227" },
    { name: "San Juan",      postal: "4226" },
    { name: "Santo Tomas",   postal: "4234" },
    { name: "Taal",          postal: "4208" },
    { name: "Talisay",       postal: "4216" },
    { name: "Taysan",        postal: "4228" },
    { name: "Tuy",           postal: "4214" },
  ],
  cavite: [
    { name: "Alfonso",       postal: "4123" },
    { name: "Amadeo",        postal: "4119" },
    { name: "Bacoor City",   postal: "4102" },
    { name: "Carmona",       postal: "4116" },
    { name: "Cavite City",   postal: "4100" },
    { name: "Dasmariñas City", postal: "4114" },
    { name: "General Trias City", postal: "4107" },
    { name: "Imus City",     postal: "4103" },
    { name: "Indang",        postal: "4122" },
    { name: "Kawit",         postal: "4104" },
    { name: "Naic",          postal: "4110" },
    { name: "Noveleta",      postal: "4105" },
    { name: "Rosario",       postal: "4106" },
    { name: "Silang",        postal: "4118" },
    { name: "Tagaytay City", postal: "4120" },
    { name: "Tanza",         postal: "4108" },
    { name: "Ternate",       postal: "4111" },
    { name: "Trece Martires City", postal: "4109" },
  ],
  laguna: [
    { name: "Bay",           postal: "4033" },
    { name: "Biñan City",    postal: "4024" },
    { name: "Cabuyao City",  postal: "4025" },
    { name: "Calamba City",  postal: "4027" },
    { name: "Calauan",       postal: "4012" },
    { name: "Los Baños",     postal: "4030" },
    { name: "Pagsanjan",     postal: "4008" },
    { name: "San Pablo City", postal: "4000" },
    { name: "San Pedro City", postal: "4023" },
    { name: "Santa Cruz",    postal: "4009" },
    { name: "Santa Rosa City", postal: "4026" },
    { name: "Victoria",      postal: "4011" },
  ],
  quezon: [
    { name: "Atimonan",      postal: "4331" },
    { name: "Candelaria",    postal: "4323" },
    { name: "Catanauan",     postal: "4311" },
    { name: "Gumaca",        postal: "4317" },
    { name: "Infanta",       postal: "4336" },
    { name: "Lopez",         postal: "4343" },
    { name: "Lucban",        postal: "4328" },
    { name: "Lucena City",   postal: "4301" },
    { name: "Pagbilao",      postal: "4302" },
    { name: "Quezon",        postal: "4315" },
    { name: "Real",          postal: "4335" },
    { name: "Sariaya",       postal: "4322" },
    { name: "Tayabas City",  postal: "4327" },
    { name: "Tiaong",        postal: "4325" },
  ],
  rizal: [
    { name: "Angono",        postal: "1930" },
    { name: "Antipolo City", postal: "1870" },
    { name: "Baras",         postal: "1970" },
    { name: "Binangonan",    postal: "1940" },
    { name: "Cainta",        postal: "1900" },
    { name: "Cardona",       postal: "1950" },
    { name: "Jalajala",      postal: "1990" },
    { name: "Morong",        postal: "1960" },
    { name: "Pililla",       postal: "1910" },
    { name: "Rodriguez (Montalban)", postal: "1860" },
    { name: "San Mateo",     postal: "1850" },
    { name: "Tanay",         postal: "1980" },
    { name: "Taytay",        postal: "1920" },
    { name: "Teresa",        postal: "1880" },
  ],
  marinduque: [
    { name: "Boac",          postal: "4900" },
    { name: "Buenavista",    postal: "4904" },
    { name: "Gasan",         postal: "4905" },
    { name: "Mogpog",        postal: "4901" },
    { name: "Santa Cruz",    postal: "4903" },
    { name: "Torrijos",      postal: "4906" },
  ],
  occ_mindoro: [
    { name: "Abra de Ilog",  postal: "5104" },
    { name: "Looc",          postal: "5102" },
    { name: "Lubang",        postal: "5099" },
    { name: "Mamburao",      postal: "5100" },
    { name: "Rizal",         postal: "5110" },
    { name: "Sablayan",      postal: "5107" },
    { name: "San Jose",      postal: "5100" },
    { name: "Santa Cruz",    postal: "5105" },
  ],
  or_mindoro: [
    { name: "Baco",          postal: "5201" },
    { name: "Bongabong",     postal: "5211" },
    { name: "Bulalacao",     postal: "5212" },
    { name: "Calapan City",  postal: "5200" },
    { name: "Gloria",        postal: "5209" },
    { name: "Mansalay",      postal: "5213" },
    { name: "Naujan",        postal: "5204" },
    { name: "Pinamalayan",   postal: "5208" },
    { name: "Puerto Galera", postal: "5203" },
    { name: "Roxas",         postal: "5207" },
    { name: "Victoria",      postal: "5206" },
  ],
  palawan: [
    { name: "Aborlan",       postal: "5302" },
    { name: "Brooke's Point", postal: "5308" },
    { name: "Coron",         postal: "5316" },
    { name: "Cuyo",          postal: "5314" },
    { name: "El Nido",       postal: "5313" },
    { name: "Narra",         postal: "5303" },
    { name: "Puerto Princesa City", postal: "5300" },
    { name: "Roxas",         postal: "5308" },
    { name: "San Vicente",   postal: "5317" },
    { name: "Taytay",        postal: "5312" },
  ],
  romblon: [
    { name: "Alcantara",     postal: "5502" },
    { name: "Cajidiocan",    postal: "5508" },
    { name: "Calatrava",     postal: "5506" },
    { name: "Looc",          postal: "5504" },
    { name: "Odiongan",      postal: "5507" },
    { name: "Romblon",       postal: "5500" },
    { name: "San Agustin",   postal: "5501" },
    { name: "Santa Fe",      postal: "5504" },
  ],
  albay: [
    { name: "Bacacay",       postal: "4509" },
    { name: "Camalig",       postal: "4502" },
    { name: "Daraga",        postal: "4501" },
    { name: "Guinobatan",    postal: "4503" },
    { name: "Jovellar",      postal: "4508" },
    { name: "Legazpi City",  postal: "4500" },
    { name: "Libon",         postal: "4512" },
    { name: "Ligao City",    postal: "4504" },
    { name: "Malilipot",     postal: "4510" },
    { name: "Malinao",       postal: "4511" },
    { name: "Oas",           postal: "4505" },
    { name: "Pio Duran",     postal: "4506" },
    { name: "Polangui",      postal: "4506" },
    { name: "Tabaco City",   postal: "4511" },
    { name: "Tiwi",          postal: "4513" },
  ],
  cam_norte: [
    { name: "Basud",         postal: "4606" },
    { name: "Capalonga",     postal: "4607" },
    { name: "Daet",          postal: "4600" },
    { name: "Jose Panganiban", postal: "4601" },
    { name: "Labo",          postal: "4604" },
    { name: "Mercedes",      postal: "4602" },
    { name: "Paracale",      postal: "4605" },
    { name: "Santa Elena",   postal: "4603" },
    { name: "Vinzons",       postal: "4606" },
  ],
  cam_sur: [
    { name: "Baao",          postal: "4432" },
    { name: "Bula",          postal: "4422" },
    { name: "Calabanga",     postal: "4405" },
    { name: "Caramoan",      postal: "4429" },
    { name: "Goa",           postal: "4422" },
    { name: "Iriga City",    postal: "4431" },
    { name: "Libmanan",      postal: "4407" },
    { name: "Lupi",          postal: "4427" },
    { name: "Naga City",     postal: "4400" },
    { name: "Pili",          postal: "4418" },
    { name: "Ragay",         postal: "4424" },
    { name: "Sipocot",       postal: "4426" },
    { name: "Tinambac",      postal: "4403" },
  ],
  catanduanes: [
    { name: "Bagamanoc",     postal: "4807" },
    { name: "Baras",         postal: "4802" },
    { name: "Bato",          postal: "4806" },
    { name: "Caramoran",     postal: "4803" },
    { name: "Pandan",        postal: "4805" },
    { name: "San Andres",    postal: "4800" },
    { name: "Virac",         postal: "4800" },
  ],
  masbate: [
    { name: "Aroroy",        postal: "5401" },
    { name: "Cataingan",     postal: "5403" },
    { name: "Cawayan",       postal: "5402" },
    { name: "Mandaon",       postal: "5408" },
    { name: "Masbate City",  postal: "5400" },
    { name: "Milagros",      postal: "5403" },
    { name: "Mobo",          postal: "5409" },
    { name: "Monreal",       postal: "5405" },
    { name: "Placer",        postal: "5402" },
    { name: "San Fernando",  postal: "5405" },
    { name: "San Jacinto",   postal: "5404" },
    { name: "Uson",          postal: "5403" },
  ],
  sorsogon: [
    { name: "Barcelona",     postal: "4712" },
    { name: "Bulan",         postal: "4707" },
    { name: "Bulusan",       postal: "4714" },
    { name: "Casiguran",     postal: "4705" },
    { name: "Castilla",      postal: "4706" },
    { name: "Donsol",        postal: "4713" },
    { name: "Gubat",         postal: "4717" },
    { name: "Irosin",        postal: "4707" },
    { name: "Juban",         postal: "4703" },
    { name: "Pilar",         postal: "4709" },
    { name: "Sorsogon City", postal: "4700" },
  ],
  aklan: [
    { name: "Altavas",       postal: "5611" },
    { name: "Batan",         postal: "5601" },
    { name: "Buruanga",      postal: "5607" },
    { name: "Ibajay",        postal: "5601" },
    { name: "Kalibo",        postal: "5600" },
    { name: "Lezo",          postal: "5603" },
    { name: "Malay",         postal: "5604" },
    { name: "Nabas",         postal: "5605" },
    { name: "New Washington", postal: "5603" },
    { name: "Numancia",      postal: "5606" },
    { name: "Tangalan",      postal: "5602" },
  ],
  antique: [
    { name: "Anini-y",       postal: "5713" },
    { name: "Barbaza",       postal: "5712" },
    { name: "Bugasong",      postal: "5718" },
    { name: "Culasi",        postal: "5705" },
    { name: "Hamtic",        postal: "5703" },
    { name: "Laua-an",       postal: "5718" },
    { name: "Pandan",        postal: "5707" },
    { name: "San Jose",      postal: "5700" },
    { name: "San Remigio",   postal: "5709" },
    { name: "Sebaste",       postal: "5710" },
    { name: "Sibalom",       postal: "5711" },
    { name: "Tibiao",        postal: "5706" },
    { name: "Valderrama",    postal: "5714" },
  ],
  capiz: [
    { name: "Dao",           postal: "5825" },
    { name: "Dumalag",       postal: "5827" },
    { name: "Dumarao",       postal: "5802" },
    { name: "Ivisan",        postal: "5822" },
    { name: "Jamindan",      postal: "5823" },
    { name: "Mambusao",      postal: "5828" },
    { name: "Panay",         postal: "5821" },
    { name: "Pilar",         postal: "5820" },
    { name: "Pontevedra",    postal: "5818" },
    { name: "Roxas City",    postal: "5800" },
    { name: "Sigma",         postal: "5814" },
    { name: "Tapaz",         postal: "5813" },
  ],
  guimaras: [
    { name: "Buenavista",    postal: "5044" },
    { name: "Jordan",        postal: "5045" },
    { name: "Nueva Valencia", postal: "5046" },
    { name: "San Lorenzo",   postal: "5047" },
    { name: "Sibunag",       postal: "5043" },
  ],
  iloilo: [
    { name: "Ajuy",          postal: "5012" },
    { name: "Alimodian",     postal: "5028" },
    { name: "Barotac Nuevo", postal: "5019" },
    { name: "Barotac Viejo", postal: "5017" },
    { name: "Cabatuan",      postal: "5025" },
    { name: "Calinog",       postal: "5024" },
    { name: "Carles",        postal: "5014" },
    { name: "Concepcion",    postal: "5013" },
    { name: "Dingle",        postal: "5022" },
    { name: "Dumangas",      postal: "5006" },
    { name: "Estancia",      postal: "5017" },
    { name: "Guimbal",       postal: "5022" },
    { name: "Iloilo City",   postal: "5000" },
    { name: "Janiuay",       postal: "5026" },
    { name: "Lambunao",      postal: "5032" },
    { name: "Leganes",       postal: "5003" },
    { name: "Leon",          postal: "5029" },
    { name: "Miagao",        postal: "5023" },
    { name: "Mina",          postal: "5027" },
    { name: "New Lucena",    postal: "5001" },
    { name: "Oton",          postal: "5020" },
    { name: "Passi City",    postal: "5037" },
    { name: "Pavia",         postal: "5001" },
    { name: "Pototan",       postal: "5008" },
    { name: "San Dionisio",  postal: "5015" },
    { name: "San Enrique",   postal: "5018" },
    { name: "San Joaquin",   postal: "5023" },
    { name: "San Miguel",    postal: "5011" },
    { name: "Santa Barbara", postal: "5002" },
    { name: "Sara",          postal: "5012" },
    { name: "Tigbauan",      postal: "5021" },
    { name: "Zarraga",       postal: "5009" },
  ],
  neg_occ: [
    { name: "Bacolod City",  postal: "6100" },
    { name: "Bago City",     postal: "6101" },
    { name: "Binalbagan",    postal: "6107" },
    { name: "Calatrava",     postal: "6126" },
    { name: "Escalante City", postal: "6124" },
    { name: "Himamaylan City", postal: "6108" },
    { name: "Hinigaran",     postal: "6106" },
    { name: "Kabankalan City", postal: "6111" },
    { name: "La Carlota City", postal: "6130" },
    { name: "Manapla",       postal: "6110" },
    { name: "Murcia",        postal: "6119" },
    { name: "Pontevedra",    postal: "6105" },
    { name: "Pulupandan",    postal: "6104" },
    { name: "Sagay City",    postal: "6122" },
    { name: "San Carlos City", postal: "6127" },
    { name: "Silay City",    postal: "6116" },
    { name: "Sipalay City",  postal: "6113" },
    { name: "Talisay City",  postal: "6115" },
    { name: "Victorias City", postal: "6119" },
  ],
  bohol: [
    { name: "Alburquerque",  postal: "6301" },
    { name: "Anda",          postal: "6311" },
    { name: "Baclayon",      postal: "6301" },
    { name: "Buenavista",    postal: "6319" },
    { name: "Calape",        postal: "6328" },
    { name: "Carmen",        postal: "6319" },
    { name: "Corella",       postal: "6301" },
    { name: "Dauis",         postal: "6339" },
    { name: "Inabanga",      postal: "6303" },
    { name: "Jagna",         postal: "6308" },
    { name: "Loay",          postal: "6321" },
    { name: "Loboc",         postal: "6317" },
    { name: "Loon",          postal: "6323" },
    { name: "Panglao",       postal: "6340" },
    { name: "Tagbilaran City", postal: "6300" },
    { name: "Talibon",       postal: "6325" },
    { name: "Tubigon",       postal: "6327" },
    { name: "Ubay",          postal: "6319" },
    { name: "Valencia",      postal: "6322" },
  ],
  cebu: [
    { name: "Alcoy",         postal: "6050" },
    { name: "Alegria",       postal: "6034" },
    { name: "Argao",         postal: "6021" },
    { name: "Asturias",      postal: "6033" },
    { name: "Badian",        postal: "6031" },
    { name: "Balamban",      postal: "6041" },
    { name: "Bantayan",      postal: "6002" },
    { name: "Barili",        postal: "6036" },
    { name: "Bogo City",     postal: "6010" },
    { name: "Carcar City",   postal: "6019" },
    { name: "Carmen",        postal: "6005" },
    { name: "Cebu City",     postal: "6000" },
    { name: "Compostela",    postal: "6003" },
    { name: "Consolacion",   postal: "6001" },
    { name: "Cordoba",       postal: "6093" },
    { name: "Daanbantayan",  postal: "6013" },
    { name: "Dalaguete",     postal: "6027" },
    { name: "Danao City",    postal: "6004" },
    { name: "Dumanjug",      postal: "6037" },
    { name: "Ginatilan",     postal: "6032" },
    { name: "Lapu-Lapu City", postal: "6015" },
    { name: "Liloan",        postal: "6002" },
    { name: "Madridejos",    postal: "6011" },
    { name: "Mandaue City",  postal: "6014" },
    { name: "Medellin",      postal: "6012" },
    { name: "Minglanilla",   postal: "6046" },
    { name: "Moalboal",      postal: "6032" },
    { name: "Naga City",     postal: "6037" },
    { name: "Oslob",         postal: "6023" },
    { name: "Ronda",         postal: "6014" },
    { name: "Samboan",       postal: "6034" },
    { name: "San Fernando",  postal: "6018" },
    { name: "San Remigio",   postal: "6008" },
    { name: "Santa Fe",      postal: "6001" },
    { name: "Santander",     postal: "6025" },
    { name: "Sibonga",       postal: "6020" },
    { name: "Sogod",         postal: "6007" },
    { name: "Tabogon",       postal: "6009" },
    { name: "Talisay City",  postal: "6045" },
    { name: "Toledo City",   postal: "6038" },
    { name: "Tuburan",       postal: "6040" },
  ],
  neg_or: [
    { name: "Amlan",         postal: "6210" },
    { name: "Ayungon",       postal: "6212" },
    { name: "Bais City",     postal: "6206" },
    { name: "Bayawan City",  postal: "6221" },
    { name: "Canlaon City",  postal: "6223" },
    { name: "Dauin",         postal: "6217" },
    { name: "Dumaguete City", postal: "6200" },
    { name: "Guihulngan City", postal: "6214" },
    { name: "Jimalalud",     postal: "6209" },
    { name: "La Libertad",   postal: "6210" },
    { name: "Mabinay",       postal: "6207" },
    { name: "Pamplona",      postal: "6208" },
    { name: "San Jose",      postal: "6205" },
    { name: "Santa Catalina", postal: "6220" },
    { name: "Siaton",        postal: "6219" },
    { name: "Sibulan",       postal: "6201" },
    { name: "Tanjay City",   postal: "6204" },
    { name: "Valencia",      postal: "6215" },
    { name: "Zamboanguita",  postal: "6218" },
  ],
  siquijor: [
    { name: "Enrique Villanueva", postal: "6227" },
    { name: "Larena",        postal: "6225" },
    { name: "Lazi",          postal: "6228" },
    { name: "Maria",         postal: "6226" },
    { name: "San Juan",      postal: "6224" },
    { name: "Siquijor",      postal: "6224" },
  ],
  biliran: [
    { name: "Almeria",       postal: "6543" },
    { name: "Biliran",       postal: "6549" },
    { name: "Caibiran",      postal: "6548" },
    { name: "Culaba",        postal: "6547" },
    { name: "Kawayan",       postal: "6544" },
    { name: "Maripipi",      postal: "6550" },
    { name: "Naval",         postal: "6540" },
  ],
  e_samar: [
    { name: "Balangiga",     postal: "6809" },
    { name: "Can-avid",      postal: "6806" },
    { name: "Dolores",       postal: "6806" },
    { name: "General MacArthur", postal: "6803" },
    { name: "Giporlos",      postal: "6809" },
    { name: "Guiuan",        postal: "6809" },
    { name: "Lawaan",        postal: "6808" },
    { name: "Mercedes",      postal: "6807" },
    { name: "Oras",          postal: "6801" },
    { name: "Salcedo",       postal: "6808" },
    { name: "San Julian",    postal: "6808" },
    { name: "Sulat",         postal: "6804" },
    { name: "Taft",          postal: "6801" },
  ],
  leyte: [
    { name: "Abuyog",        postal: "6510" },
    { name: "Alangalang",    postal: "6511" },
    { name: "Albuera",       postal: "6503" },
    { name: "Baybay City",   postal: "6521" },
    { name: "Burauen",       postal: "6516" },
    { name: "Carigara",      postal: "6510" },
    { name: "Dagami",        postal: "6514" },
    { name: "Dulag",         postal: "6512" },
    { name: "Hilongos",      postal: "6524" },
    { name: "Isabel",        postal: "6516" },
    { name: "Jaro",          postal: "6516" },
    { name: "Kananga",       postal: "6506" },
    { name: "Leyte",         postal: "6516" },
    { name: "Merida",        postal: "6509" },
    { name: "Ormoc City",    postal: "6541" },
    { name: "Palo",          postal: "6501" },
    { name: "Palompon",      postal: "6507" },
    { name: "Tacloban City", postal: "6500" },
    { name: "Tanauan",       postal: "6516" },
    { name: "Villaba",       postal: "6516" },
  ],
  n_samar: [
    { name: "Allen",         postal: "6406" },
    { name: "Bobon",         postal: "6405" },
    { name: "Catarman",      postal: "6400" },
    { name: "Catubig",       postal: "6404" },
    { name: "Gamay",         postal: "6403" },
    { name: "Laoang",        postal: "6402" },
    { name: "Las Navas",     postal: "6403" },
    { name: "Lavezares",     postal: "6404" },
    { name: "Mondragon",     postal: "6406" },
    { name: "Palapag",       postal: "6404" },
    { name: "Pambujan",      postal: "6406" },
    { name: "Rosario",       postal: "6406" },
    { name: "San Antonio",   postal: "6405" },
    { name: "Victoria",      postal: "6407" },
  ],
  samar: [
    { name: "Basey",         postal: "6719" },
    { name: "Calbayog City", postal: "6710" },
    { name: "Catbalogan City", postal: "6700" },
    { name: "Daram",         postal: "6706" },
    { name: "Gandara",       postal: "6716" },
    { name: "Jiabong",       postal: "6700" },
    { name: "Marabut",       postal: "6720" },
    { name: "Paranas",       postal: "6718" },
    { name: "San Jorge",     postal: "6710" },
    { name: "Santa Rita",    postal: "6716" },
    { name: "Tarangnan",     postal: "6716" },
    { name: "Villareal",     postal: "6715" },
    { name: "Wright",        postal: "6714" },
  ],
  s_leyte: [
    { name: "Bontoc",        postal: "6628" },
    { name: "Hinunangan",    postal: "6625" },
    { name: "Libagon",       postal: "6623" },
    { name: "Liloan",        postal: "6631" },
    { name: "Limasawa",      postal: "6616" },
    { name: "Maasin City",   postal: "6600" },
    { name: "Macrohon",      postal: "6614" },
    { name: "Malitbog",      postal: "6608" },
    { name: "Padre Burgos",  postal: "6619" },
    { name: "Pintuyan",      postal: "6621" },
    { name: "Saint Bernard", postal: "6622" },
    { name: "San Francisco", postal: "6617" },
    { name: "San Juan",      postal: "6616" },
    { name: "Silago",        postal: "6624" },
    { name: "Sogod",         postal: "6606" },
    { name: "Tomas Oppus",   postal: "6613" },
  ],
  zamboanga_city: [
    { name: "Zamboanga City", postal: "7000" },
  ],
  zam_norte: [
    { name: "Dapitan City",  postal: "7101" },
    { name: "Dipolog City",  postal: "7100" },
    { name: "Katipunan",     postal: "7103" },
    { name: "La Libertad",   postal: "7103" },
    { name: "Labason",       postal: "7108" },
    { name: "Liloy",         postal: "7110" },
    { name: "Manukan",       postal: "7104" },
    { name: "Mutia",         postal: "7108" },
    { name: "Piñan",         postal: "7107" },
    { name: "Polanco",       postal: "7106" },
    { name: "Rizal",         postal: "7104" },
    { name: "Salug",         postal: "7112" },
    { name: "San Miguel",    postal: "7110" },
    { name: "Siayan",        postal: "7115" },
    { name: "Sindangan",     postal: "7112" },
    { name: "Siocon",        postal: "7101" },
    { name: "Tampilisan",    postal: "7109" },
  ],
  zam_sur: [
    { name: "Aurora",        postal: "7018" },
    { name: "Bayog",         postal: "7018" },
    { name: "Dimataling",    postal: "7019" },
    { name: "Dinas",         postal: "7017" },
    { name: "Dumalinao",     postal: "7015" },
    { name: "Dumingag",      postal: "7027" },
    { name: "Guipos",        postal: "7020" },
    { name: "Labangan",      postal: "7017" },
    { name: "Lapuyan",       postal: "7014" },
    { name: "Mahayag",       postal: "7016" },
    { name: "Margosatubig",  postal: "7016" },
    { name: "Midsalip",      postal: "7021" },
    { name: "Molave",        postal: "7023" },
    { name: "Pagadian City", postal: "7016" },
    { name: "San Miguel",    postal: "7021" },
    { name: "Sominot",       postal: "7022" },
    { name: "Tabina",        postal: "7020" },
    { name: "Tambulig",      postal: "7027" },
    { name: "Tukuran",       postal: "7018" },
  ],
  zam_sibugay: [
    { name: "Alicia",        postal: "7019" },
    { name: "Buug",          postal: "7003" },
    { name: "Diplahan",      postal: "7011" },
    { name: "Imelda",        postal: "7003" },
    { name: "Ipil",          postal: "7001" },
    { name: "Kabasalan",     postal: "7005" },
    { name: "Mabuhay",       postal: "7002" },
    { name: "Malangas",      postal: "7013" },
    { name: "Naga",          postal: "7004" },
    { name: "Olutanga",      postal: "7014" },
    { name: "Payao",         postal: "7006" },
    { name: "Siay",          postal: "7009" },
    { name: "Talusan",       postal: "7008" },
    { name: "Titay",         postal: "7010" },
    { name: "Tungawan",      postal: "7007" },
  ],
  bukidnon: [
    { name: "Baungon",       postal: "8727" },
    { name: "Damulog",       postal: "8706" },
    { name: "Dangcagan",     postal: "8707" },
    { name: "Don Carlos",    postal: "8700" },
    { name: "Impasug-ong",   postal: "8700" },
    { name: "Kadingilan",    postal: "8706" },
    { name: "Kibawe",        postal: "8709" },
    { name: "Kitaotao",      postal: "8707" },
    { name: "Lantapan",      postal: "8700" },
    { name: "Libona",        postal: "8728" },
    { name: "Manolo Fortich", postal: "8703" },
    { name: "Maramag",       postal: "8710" },
    { name: "Quezon",        postal: "8706" },
    { name: "San Fernando",  postal: "8741" },
    { name: "Sumilao",       postal: "8705" },
    { name: "Talakag",       postal: "8712" },
    { name: "Valencia City", postal: "8709" },
  ],
  camiguin: [
    { name: "Catarman",      postal: "9100" },
    { name: "Guinsiliban",   postal: "9101" },
    { name: "Mahinog",       postal: "9102" },
    { name: "Mambajao",      postal: "9100" },
    { name: "Sagay",         postal: "9103" },
  ],
  lanao_norte: [
    { name: "Bacolod",       postal: "9210" },
    { name: "Iligan City",   postal: "9200" },
    { name: "Kapatagan",     postal: "9214" },
    { name: "Kauswagan",     postal: "9207" },
    { name: "Kolambugan",    postal: "9210" },
    { name: "Lala",          postal: "9216" },
    { name: "Linamon",       postal: "9213" },
    { name: "Magsaysay",     postal: "9212" },
    { name: "Maigo",         postal: "9206" },
    { name: "Munai",         postal: "9211" },
    { name: "Nunungan",      postal: "9218" },
    { name: "Pantao Ragat",  postal: "9217" },
    { name: "Pantar",        postal: "9220" },
    { name: "Poona Piagapo", postal: "9221" },
    { name: "Salvador",      postal: "9209" },
    { name: "Sapad",         postal: "9219" },
    { name: "Sultan Naga Dimaporo", postal: "9208" },
    { name: "Tagoloan",      postal: "9222" },
    { name: "Tangcal",       postal: "9214" },
    { name: "Tubod",         postal: "9201" },
  ],
  mis_occ: [
    { name: "Aloran",        postal: "7207" },
    { name: "Baliangao",     postal: "7218" },
    { name: "Bonifacio",     postal: "7212" },
    { name: "Calamba",       postal: "7214" },
    { name: "Clarin",        postal: "7219" },
    { name: "Jimenez",       postal: "7209" },
    { name: "Lopez Jaena",   postal: "7215" },
    { name: "Oroquieta City", postal: "7207" },
    { name: "Ozamiz City",   postal: "7200" },
    { name: "Sinacaban",     postal: "7201" },
    { name: "Tangub City",   postal: "7214" },
    { name: "Tudela",        postal: "7214" },
  ],
  mis_or: [
    { name: "Alubijid",      postal: "9003" },
    { name: "Balingasag",    postal: "9005" },
    { name: "Cagayan de Oro City", postal: "9000" },
    { name: "Claveria",      postal: "9004" },
    { name: "El Salvador City", postal: "9017" },
    { name: "Gingoog City",  postal: "9014" },
    { name: "Gitagum",       postal: "9002" },
    { name: "Initao",        postal: "9008" },
    { name: "Jasaan",        postal: "9003" },
    { name: "Laguindingan",  postal: "9019" },
    { name: "Lugait",        postal: "9011" },
    { name: "Manticao",      postal: "9014" },
    { name: "Medina",        postal: "9013" },
    { name: "Naawan",        postal: "9023" },
    { name: "Opol",          postal: "9016" },
    { name: "Salay",         postal: "9007" },
    { name: "Tagoloan",      postal: "9001" },
    { name: "Talisayan",     postal: "9013" },
    { name: "Villanueva",    postal: "9001" },
  ],
  comval: [
    { name: "Compostela",    postal: "8800" },
    { name: "Laak",          postal: "8803" },
    { name: "Mabini",        postal: "8812" },
    { name: "Maco",          postal: "8808" },
    { name: "Maragusan",     postal: "8803" },
    { name: "Mawab",         postal: "8806" },
    { name: "Monkayo",       postal: "8807" },
    { name: "Montevista",    postal: "8809" },
    { name: "Nabunturan",    postal: "8800" },
    { name: "New Bataan",    postal: "8802" },
    { name: "Pantukan",      postal: "8808" },
  ],
  davao_city: [
    { name: "Davao City",    postal: "8000" },
  ],
  davao_norte: [
    { name: "Asuncion",      postal: "8105" },
    { name: "Braulio E. Dujali", postal: "8105" },
    { name: "Carmen",        postal: "8107" },
    { name: "Kapalong",      postal: "8112" },
    { name: "New Corella",   postal: "8106" },
    { name: "Panabo City",   postal: "8105" },
    { name: "San Isidro",    postal: "8111" },
    { name: "Santo Tomas",   postal: "8112" },
    { name: "Tagum City",    postal: "8100" },
    { name: "Talaingod",     postal: "8113" },
  ],
  davao_sur: [
    { name: "Bansalan",      postal: "8005" },
    { name: "Davao City",    postal: "8000" },
    { name: "Digos City",    postal: "8002" },
    { name: "Hagonoy",       postal: "8006" },
    { name: "Kiblawan",      postal: "8007" },
    { name: "Magsaysay",     postal: "8004" },
    { name: "Malalag",       postal: "8003" },
    { name: "Matanao",       postal: "8009" },
    { name: "Padada",        postal: "8008" },
    { name: "Santa Cruz",    postal: "8003" },
    { name: "Sulop",         postal: "8002" },
  ],
  davao_occ: [
    { name: "Don Marcelino", postal: "8008" },
    { name: "Jose Abad Santos", postal: "8006" },
    { name: "Malita",        postal: "8007" },
    { name: "Sarangani",     postal: "8001" },
    { name: "Santa Maria",   postal: "8007" },
  ],
  davao_or: [
    { name: "Baganga",       postal: "8200" },
    { name: "Banaybanay",    postal: "8209" },
    { name: "Boston",        postal: "8202" },
    { name: "Caraga",        postal: "8204" },
    { name: "Cateel",        postal: "8203" },
    { name: "Governor Generoso", postal: "8209" },
    { name: "Lupon",         postal: "8208" },
    { name: "Manay",         postal: "8204" },
    { name: "Mati City",     postal: "8200" },
    { name: "San Isidro",    postal: "8201" },
    { name: "Tarragona",     postal: "8205" },
  ],
  cotabato: [
    { name: "Alamada",       postal: "9405" },
    { name: "Aleosan",       postal: "9403" },
    { name: "Antipas",       postal: "9404" },
    { name: "Arakan",        postal: "9404" },
    { name: "Banisilan",     postal: "9402" },
    { name: "Carmen",        postal: "9407" },
    { name: "Kabacan",       postal: "9407" },
    { name: "Kidapawan City", postal: "9400" },
    { name: "Libungan",      postal: "9410" },
    { name: "Makilala",      postal: "9401" },
    { name: "Magpet",        postal: "9401" },
    { name: "Matalam",       postal: "9404" },
    { name: "Midsayap",      postal: "9410" },
    { name: "Mlang",         postal: "9406" },
    { name: "Pigcawayan",    postal: "9409" },
    { name: "Pikit",         postal: "9408" },
    { name: "President Roxas", postal: "9404" },
    { name: "Tulunan",       postal: "9405" },
  ],
  sarangani: [
    { name: "Alabel",        postal: "9501" },
    { name: "Glan",          postal: "9501" },
    { name: "Kiamba",        postal: "9501" },
    { name: "Maasim",        postal: "9501" },
    { name: "Maitum",        postal: "9501" },
    { name: "Malungon",      postal: "9501" },
    { name: "Malapatan",     postal: "9501" },
  ],
  s_cotabato: [
    { name: "Banga",         postal: "9515" },
    { name: "General Santos City", postal: "9500" },
    { name: "Koronadal City", postal: "9506" },
    { name: "Lake Sebu",     postal: "9508" },
    { name: "Norala",        postal: "9517" },
    { name: "Polomolok",     postal: "9504" },
    { name: "Santo Niño",    postal: "9507" },
    { name: "Surallah",      postal: "9512" },
    { name: "T'boli",        postal: "9519" },
    { name: "Tampakan",      postal: "9516" },
    { name: "Tantangan",     postal: "9510" },
    { name: "Tupi",          postal: "9505" },
  ],
  sultan_kudarat: [
    { name: "Bagumbayan",    postal: "9805" },
    { name: "Columbio",      postal: "9808" },
    { name: "Esperanza",     postal: "9806" },
    { name: "Isulan",        postal: "9801" },
    { name: "Kalamansig",    postal: "9806" },
    { name: "Lambayong",     postal: "9806" },
    { name: "Lebak",         postal: "9807" },
    { name: "Lutayan",       postal: "9806" },
    { name: "Palimbang",     postal: "9805" },
    { name: "President Quirino", postal: "9801" },
    { name: "Senator Ninoy Aquino", postal: "9804" },
    { name: "Sultan Kudarat", postal: "9808" },
    { name: "Tacurong City", postal: "9800" },
  ],
  agusan_norte: [
    { name: "Buenavista",    postal: "8602" },
    { name: "Butuan City",   postal: "8600" },
    { name: "Cabadbaran City", postal: "8605" },
    { name: "Carmen",        postal: "8601" },
    { name: "Jabonga",       postal: "8602" },
    { name: "Kitcharao",     postal: "8604" },
    { name: "Las Nieves",    postal: "8603" },
    { name: "Magallanes",    postal: "8604" },
    { name: "Nasipit",       postal: "8602" },
    { name: "Santiago",      postal: "8603" },
    { name: "Tubay",         postal: "8601" },
  ],
  agusan_sur: [
    { name: "Bayugan City",  postal: "8502" },
    { name: "Bunawan",       postal: "8510" },
    { name: "Esperanza",     postal: "8516" },
    { name: "La Paz",        postal: "8516" },
    { name: "Loreto",        postal: "8509" },
    { name: "Prosperidad",   postal: "8500" },
    { name: "San Francisco", postal: "8501" },
    { name: "Santa Josefa",  postal: "8517" },
    { name: "Sibagat",       postal: "8516" },
    { name: "Trento",        postal: "8504" },
    { name: "Veruela",       postal: "8516" },
  ],
  dinagat: [
    { name: "Basilisa",      postal: "8426" },
    { name: "Cagdianao",     postal: "8423" },
    { name: "Dinagat",       postal: "8427" },
    { name: "Libjo",         postal: "8425" },
    { name: "Loreto",        postal: "8424" },
    { name: "San Jose",      postal: "8424" },
    { name: "Tubajon",       postal: "8421" },
  ],
  surigao_norte: [
    { name: "Bacuag",        postal: "8403" },
    { name: "Claver",        postal: "8405" },
    { name: "Dapa",          postal: "8418" },
    { name: "Del Carmen",    postal: "8419" },
    { name: "General Luna",  postal: "8419" },
    { name: "Gigaquit",      postal: "8407" },
    { name: "Mainit",        postal: "8402" },
    { name: "Malimono",      postal: "8408" },
    { name: "Placer",        postal: "8401" },
    { name: "San Benito",    postal: "8417" },
    { name: "San Francisco", postal: "8418" },
    { name: "Santa Monica",  postal: "8405" },
    { name: "Sison",         postal: "8413" },
    { name: "Socorro",       postal: "8419" },
    { name: "Surigao City",  postal: "8400" },
    { name: "Tagana-an",     postal: "8405" },
    { name: "Tubod",         postal: "8409" },
  ],
  surigao_sur: [
    { name: "Barobo",        postal: "8317" },
    { name: "Bayabas",       postal: "8312" },
    { name: "Bislig City",   postal: "8311" },
    { name: "Cagwait",       postal: "8316" },
    { name: "Cantilan",      postal: "8315" },
    { name: "Carmen",        postal: "8313" },
    { name: "Carrascal",     postal: "8314" },
    { name: "Cortes",        postal: "8313" },
    { name: "Hinatuan",      postal: "8300" },
    { name: "Lanuza",        postal: "8315" },
    { name: "Lianga",        postal: "8308" },
    { name: "Lingig",        postal: "8310" },
    { name: "Madrid",        postal: "8317" },
    { name: "San Agustin",   postal: "8307" },
    { name: "San Miguel",    postal: "8309" },
    { name: "Tagbina",       postal: "8318" },
    { name: "Tago",          postal: "8316" },
    { name: "Tandag City",   postal: "8300" },
  ],
  basilan: [
    { name: "Akbar",         postal: "7304" },
    { name: "Al-Barka",      postal: "7305" },
    { name: "Hadji Mohammad Ajul", postal: "7300" },
    { name: "Isabela City",  postal: "7300" },
    { name: "Lamitan City",  postal: "7302" },
    { name: "Lantawan",      postal: "7300" },
    { name: "Maluso",        postal: "7303" },
    { name: "Sumisip",       postal: "7301" },
    { name: "Tipo-Tipo",     postal: "7300" },
    { name: "Tuburan",       postal: "7307" },
  ],
  lanao_sur: [
    { name: "Bacolod-Kalawi", postal: "9700" },
    { name: "Balabagan",     postal: "9716" },
    { name: "Binidayan",     postal: "9700" },
    { name: "Ganassi",       postal: "9717" },
    { name: "Kapai",         postal: "9701" },
    { name: "Lumba-Bayabao", postal: "9718" },
    { name: "Lumbatan",      postal: "9715" },
    { name: "Maguing",       postal: "9711" },
    { name: "Malabang",      postal: "9711" },
    { name: "Marantao",      postal: "9701" },
    { name: "Marawi City",   postal: "9700" },
    { name: "Masiu",         postal: "9706" },
    { name: "Mulondo",       postal: "9715" },
    { name: "Piagapo",       postal: "9703" },
    { name: "Tamparan",      postal: "9708" },
    { name: "Taraka",        postal: "9715" },
    { name: "Tubaran",       postal: "9715" },
    { name: "Tugaya",        postal: "9715" },
    { name: "Wao",           postal: "9711" },
  ],
  maguindanao_n: [
    { name: "Barira",        postal: "9604" },
    { name: "Buldon",        postal: "9606" },
    { name: "Datu Blah T. Sinsuat", postal: "9604" },
    { name: "Datu Odin Sinsuat", postal: "9603" },
    { name: "Kabuntalan",    postal: "9604" },
    { name: "Matanog",       postal: "9604" },
    { name: "Northern Kabuntalan", postal: "9604" },
    { name: "Parang",        postal: "9604" },
    { name: "Sultan Mastura", postal: "9604" },
    { name: "Upi",           postal: "9614" },
  ],
  maguindanao_s: [
    { name: "Ampatuan",      postal: "9602" },
    { name: "Buluan",        postal: "9608" },
    { name: "Datu Abdullah Sangki", postal: "9600" },
    { name: "Datu Piang",    postal: "9615" },
    { name: "Datu Salibo",   postal: "9614" },
    { name: "General Salipada K. Pendatun", postal: "9608" },
    { name: "Guindulungan",  postal: "9614" },
    { name: "Mamasapano",    postal: "9603" },
    { name: "Mangudadatu",   postal: "9608" },
    { name: "Pagalungan",    postal: "9605" },
    { name: "Rajah Buayan",  postal: "9614" },
    { name: "Shariff Aguak", postal: "9600" },
    { name: "Sultan Ibrahim", postal: "9600" },
    { name: "Sultan Kudarat", postal: "9603" },
    { name: "Talayan",       postal: "9614" },
  ],
  sulu: [
    { name: "Hadji Panglima Tahil", postal: "7402" },
    { name: "Indanan",       postal: "7400" },
    { name: "Jolo",          postal: "7400" },
    { name: "Luuk",          postal: "7407" },
    { name: "Maimbung",      postal: "7407" },
    { name: "Panamao",       postal: "7410" },
    { name: "Patikul",       postal: "7401" },
    { name: "Siasi",         postal: "7416" },
    { name: "Talipao",       postal: "7409" },
    { name: "Tapul",         postal: "7411" },
  ],
  tawi_tawi: [
    { name: "Bongao",        postal: "7500" },
    { name: "Languyan",      postal: "7504" },
    { name: "Mapun",         postal: "7508" },
    { name: "Panglima Sugala", postal: "7506" },
    { name: "Sapa-Sapa",     postal: "7505" },
    { name: "Simunul",       postal: "7501" },
    { name: "Sitangkai",     postal: "7507" },
    { name: "South Ubian",   postal: "7503" },
    { name: "Tandubas",      postal: "7509" },
    { name: "Turtle Islands", postal: "7510" },
  ],
};
